struct ButtonColors {
    base: color,
    pressed: color,
    hovered: color,
}

export global palette {
    in property <bool> night-mode: false;
    out property <color> text: night-mode ? #000000 : #FFFFFF;
    out property <color> main: #ff6f00;
    out property <color> background: #2e2d2d;
    out property <color> primary-push-button-base: #ff0000;
    out property <ButtonColors> primary-push-button-colors: {
        base: root.primary-push-button-base,
        pressed: root.primary-push-button-base.darker(40%),
        hovered: root.primary-push-button-base.darker(20%),
    };
    
}

export component Page inherits Rectangle{
    background: palette.background;
    callback back();
    
}

export global pageination {
    in-out property <int> activepage : 0;
}

export component BackToDashBoard {
    x: 0;
    y: 0;
    width: 20px;
    height: 20px;
    Rectangle {
        background: red;
        Text {
            text: "X";
        }
        
        TouchArea {
            width: parent.width;
            height: parent.height;
            clicked => {
                pageination.activepage = 0;
            }
        }
    }
}