import { GridBox, Button, Slider } from "std-widgets.slint";
import { palette } from "./common.slint";

export component AppWindow inherits Window {
    background: @linear-gradient(45deg, palette.background 20%, palette.main 100%);
    width: 1600px;
    height: 900px;
    in-out property <bool> sidebaractive: true;
    in-out property <int> activepage;
    in-out property <int> sbwidth;
    // should only be shown if sidebaractive is true
        sidebar := Rectangle {
        height: 100%;
        animate width { duration: 150ms; }
        width: sidebaractive ? 20% : 0%;
        background: #ffffff3e;
        padding: 0;
        x: 0px;
        sidebarbutton := Button {
            x: sidebaractive ? sidebar.width - 35px : sidebar.width;
            y: 0px;
            icon: @image-url("ui/assets/arrow-right.svg");
            text: ">";
            clicked => {
                sidebaractive = ! sidebaractive;
            }
        }
    }

    GridBox {
        padding-left: sidebar.width + 20px;
        padding: 20px;
        Row {
            Button {
                
                padding: 100px;
                text: "Snake";
            }

            Button {
                text: "Pong";
            }
        }

        Row {
            Button {
                text: "BrickBreaker";
            }

            Button {
                text: "Platformer";
            }
        }
    }
}
