import {palette, Page, properties} from "common.slint";
//import "C:\Users\teisb\AppData\Local\Microsoft\Windows\Fonts/RandyGGRegular.ttf";

component LeaderboardSlot inherits Rectangle {
    VerticalLayout {
        spacing: 20px;
        for user in properties.user: Rectangle {
            background: @linear-gradient(45deg, blue 0%, palette.main 50%, palette.background 100%);
            height: parent.height/10;
            width: parent.width*0.9;
            border-width: 1px;
            border-color: #6e68687d;
            border-radius: 20px;
            Text {
                font-family: "RandyGG";
                x: parent.width*0.05;
                font-size: parent.height/3;
                color: #e9e2e2;
                text: @tr("{}", user.name);
                vertical-alignment: center;
                horizontal-alignment: center;
            }
            
            Text {
                x: 20px + parent.width / 2;
                font-family: "RandyGG";
                font-size: parent.height/3;
                color: #ffffff;
                text: @tr("score: {}", user.score);
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }
}

export component leaderboard{

    min-height: 400px;

        padding-left: 5px;
        Rectangle {
            x: parent.width*0;
            width: root.width >= 500px ? parent.width/3 : parent.width;
            Text {
                y:5px;
                Rectangle {

                }
                text: "Snake";
            }
            LeaderboardSlot {
                y: parent.height/20;
            }
        }
        if root.width >= 500px :Rectangle {
            x: parent.width/3;

            width: parent.width/3;
            Text {
                y:5px;
                text: "Pong";
            }
            LeaderboardSlot {
                y: parent.height/20;
            }
        }    
        if root.width >= 900px : Rectangle {
            x: parent.width/3*2;
            width: parent.width/3;
            Text {
                y:5px;
                text: "Brick Breaker";
            }
            LeaderboardSlot {
                y: parent.height/20;
            }
        }    
    }


