import { Button, VerticalBox, LineEdit, ProgressIndicator } from "std-widgets.slint";
import { Page, pageination, BackToDashBoard, callbacks, properties } from "common.slint";




export component LoginPage inherits Page {
    height: 100%;
    width: 100%;
    BackToDashBoard { }

    VerticalBox {
        width: root.width;
        height: parent.height;
        usernamefield := LineEdit {
            height: root.height / 3;
            placeholder-text: "username";
            text: "";
        }

        passwordfield := LineEdit {
            height: root.height / 3;
            placeholder-text: "password";
            input-type: password;
            text: "";
        }

        loginbutton := Button {
            height: root.height / 10;
            text: "Login";
            clicked => {
                properties.currentuser.username = usernamefield.text;
                properties.currentuser.password = passwordfield.text;
                properties.token = callbacks.request-login(properties.currentuser);
                if (properties.token != "") {
                    properties.logged-in = true;
                }
            }
        }

        accountbtn := Button {
            text: "Create new account";
            clicked => {
                pageination.activepage = 1;
            }
        }
    }
}
