import { Button, VerticalBox, LineEdit, ProgressIndicator } from "std-widgets.slint";


export struct User {
    username: string,
    password: string,
}

export component AppWindow inherits Window {
    height: 1080px;
    width: 1920px;
    out property <User> currentuser;
    out property <bool> name;
    callback request-login(User);
    callback request-create-user(User);
    callback create-account-btn <=> accountbtn.clicked;
    VerticalBox {
        width: 600px;
        height: 400px;
        usernamefield := LineEdit {
            height: parent.height / 3;
            placeholder-text: "username";
            text: "";
        }

        passwordfield := LineEdit {
            height: parent.height / 3;
            placeholder-text: "password";
            input-type: password;
            text: "";
        }

        loginbutton := Button {
            height: parent.height / 10;
            text: "Login";
            clicked => {
                root.currentuser.username = usernamefield.text;
                root.currentuser.password = passwordfield.text;
                root.request-login(currentuser);
            }
        }
    }

    accountbtn := Button {
        text: "Create new account";
        clicked => {
            name = true;
        }
    }
}
