import {palette, pageination, callbacks, properties, Credentials, User} from "./common.slint";
import { LoginPage } from "login.slint";
import { SignUpPage } from "signup.slint";
import { Dashboard } from "dashboard.slint";
import { Button } from "std-widgets.slint";
import { leaderboard } from "leaderboards.slint";
import { Profile } from "profile.slint";

export global logic {
    in-out property <string> token <=> properties.token;
    in-out property <bool> loading <=> properties.loading;
    in-out property <[User]> value <=> properties.user;
}

export component AppWindow inherits Window {
    min-height: 480px;
    min-width: 480px;
    callback login <=> callbacks.request-login;
    callback createacc <=> callbacks.request-create-user;
    callback gethighscoresperuser <=> callbacks.get-user-scores;
    pure callback gethighscores <=> callbacks.get-scores;
    //possibly make it states based rather than if statements
   main := HorizontalLayout {
        alignment: stretch;
        width: properties.sidebaractive ? 80% : 100%;
        x: sidebar.width;
        if pageination.activepage == 0: Dashboard {
            visible: true;
        }
        if pageination.activepage == 1: SignUpPage {
            visible: true;
        }
        if pageination.activepage == 2: LoginPage {
            visible: true;
        }
        if pageination.activepage == 3 && properties.logged-in == true: test:=leaderboard {
            visible: true;
        }
        if pageination.activepage == 4: Profile {
            visible: true;
        }
    }

    //TODO: Make the SVG scale depedending on the scale of the window
    sidebar := Rectangle {
        visible: properties.sidebartest ? true : false;
        x: 0px;
        y: 0px;
        width: properties.sidebaractive ? 20% : 0%;
        height: 100%;
        background: palette.background;
        padding: 0;
        sidebarbutton := TouchArea {
            x: properties.sidebaractive ? sidebar.width - 20px : sidebar.width - 10px;
            y: 0px;
            width: 30px;
            Image {
                source: properties.sidebaractive ? @image-url("C:/Users/teisb/desktop/TxP/h3-projektv2-24q2h3-gruppe3-txp/Frontend/user_interface/ui/assets/arrow-left.svg") : @image-url("C:/Users/teisb/desktop/TxP/h3-projektv2-24q2h3-gruppe3-txp/Frontend/user_interface/ui/assets/arrow-right.svg");
                height: 20px;
                width: 20px;
                colorize: white;
            }

            clicked => {
                properties.sidebaractive = ! properties.sidebaractive;
            }
        }

        // Currently login
        Rectangle {
            visible: properties.sidebaractive ? true : false;
            Text {
                text: "clickme";
                TouchArea {
                    width: 150%;
                    height: 150%;
                    clicked => {
                        pageination.activepage = 2;
                        properties.sidebartest = false;
                        properties.sidebaractive = false;
                    }
                }
            }
        }

        //leaderboards or highscore
        Rectangle {
            y: -0.325 * parent.height;
            visible: properties.sidebaractive ? true : false;
            TouchArea {
                height: 25px;
                width: 25px;
                Rectangle {
                    Image {
                        source: @image-url("C:/Users/teisb/desktop/TxP/h3-projektv2-24q2h3-gruppe3-txp/Frontend/user_interface/ui/assets/trophy.svg");
                        width: 100%;
                        height: 100%;
                        states [
                            active when pageination.activepage == 3: {
                                colorize: palette.main;
                            }
                            inactive when pageination.activepage != 3: {
                                colorize: palette.inactive;
                            }
                        ]
                    }
                }

                clicked => {
                    pageination.activepage = 3;
                    properties.sidebartest = true;
                    properties.sidebaractive = true;
                        callbacks.get-scores(1, properties.token);
                }
            }
        }

        //dashboard
        Rectangle {
            y: -0.4 * parent.height;
            visible: properties.sidebaractive ? true : false;
            TouchArea {
                height: 25px;
                width: 25px;
                Rectangle {
                    Image {
                        source: @image-url("C:/Users/teisb/desktop/TxP/h3-projektv2-24q2h3-gruppe3-txp/Frontend/user_interface/ui/assets/home.svg");
                        width: 100%;
                        height: 100%;
                        states [
                            active when pageination.activepage == 0: {
                                colorize: palette.main;
                            }
                            inactive when pageination.activepage != 0: {
                                colorize: palette.inactive;
                            }
                        ]
                    }
                }

                clicked => {
                    pageination.activepage = 0;
                    properties.sidebartest = true;
                    properties.sidebaractive = true;
                }
            }
        }

        //User
        Rectangle {
            y: -0.25 * parent.height;
            visible: properties.sidebaractive ? true : false;
            TouchArea {
                height: 25px;
                width: 25px;
                Rectangle {
                    Image {
                        source: @image-url("C:/Users/teisb/desktop/TxP/h3-projektv2-24q2h3-gruppe3-txp/Frontend/user_interface/ui/assets/user.svg");
                        width: 100%;
                        height: 100%;
                        states [
                            active when pageination.activepage == 4: {
                                colorize: palette.main;
                            }
                            inactive when pageination.activepage != 4: {
                                colorize: palette.inactive;
                            }
                        ]
                    }
                }

                clicked => {
                    pageination.activepage = 4;
                    properties.sidebartest = true;
                    properties.sidebaractive = true;
                }
            }
        }

        //log out btn
        if properties.logged-in: Rectangle {
            y: 0.4 * parent.height;
            visible: properties.sidebaractive ? true : false;
            TouchArea {
                height: 25px;
                width: 25px;
                Rectangle {
                    Image {
                        source: @image-url("C:/Users/teisb/desktop/TxP/h3-projektv2-24q2h3-gruppe3-txp/Frontend/user_interface/ui/assets/user.svg");
                        width: 100%;
                        height: 100%;
                        colorize: white;
                    }
                }

                clicked => {
                    pageination.activepage = 0;
                    properties.sidebartest = true;
                    properties.sidebaractive = true;
                }
            }
        }
    }
}
