import {palette, pageination, callbacks, properties, Credentials} from "./common.slint";
import { Page } from "common.slint";

export component Profile {
    width: 1000px;
    height: 800px;
    userlabel := Rectangle {
        width: 95%;
        height: 10%;
        background: red;
        x: parent.width * 0.025;
        y: 10px;
        border-color: blue;
        border-width: 2px;
        Text {
            x: parent.width/3;
            y: parent.height/3;
            font-size: 20px;
            text: @tr("{}test", properties.currentuser.username);
        }

        //need to get current date
        Text {
            x: parent.width * 0.90;
            y: parent.height / 3;
            text: @tr("{}", properties.date);
        }

        Text {
            x: parent.width * 0.90;
            y: parent.height * 2 / 3;
            text: @tr("{}",properties.time);
        }
    }

    topscores := Rectangle {
        background: red;
        height: 40%;
        width: 40%;
        x: parent.width * 0.025;
        y: parent.height / 7;
        for game in properties.games: Rectangle {
            Text {
                //   text: @tr("{}", game.score);
                text: @tr("test" );
            }
        }
    }

    gamescores := Rectangle {
        background: red;
        height: 80%;
        width: parent.width/3;
        x: parent.width * 0.6;
        y: parent.height / 7;
        VerticalLayout {
            for game in properties.games: Rectangle {
                test :=Text {
                    text: @tr("{}:", game);
                }
                Text {
                    y: test.y + 15px;
                    text: @tr("{}", "test");
                }
            }
        }
    }
}
